Features/adjust user profile
byteleaf/companyon pull request #82
Opened 2021-04-06 16:41 UTC by simon-ittmann

2021-04-07 07:35 UTC, ptolstoi requested changes
overall, looks good to me :) just a few comments

2021-04-07 07:35 UTC, ptolstoi commented on backend/src/main/kotlin/de/byteleaf/companyon/user/constant/ProvinceGermany.kt
> +    NORDREIN_WESTFALEN,
Nordrhein*

2021-04-07 07:35 UTC, ptolstoi commented on backend/src/main/kotlin/de/byteleaf/companyon/user/constant/ProvinceGermany.kt
> +    BAYERN_AUGSBURG,
I don't know this bundesland? :D

2021-04-07 07:35 UTC, ptolstoi commented on backend/src/main/kotlin/de/byteleaf/companyon/user/dto/User.kt
> +    val province: ProvinceGermany
what are the plans to make this more generic?

2021-04-07 07:51 UTC, markus-heer commented on backend/src/main/kotlin/de/byteleaf/companyon/user/constant/ProvinceGermany.kt
> +    BAYERN_AUGSBURG,
Augsburg must be treated differently because of an additional vacation day. This will be enhanced in the future and is rather a MVP approach we aligned on

2021-04-07 07:52 UTC, markus-heer commented on backend/src/main/kotlin/de/byteleaf/companyon/user/dto/User.kt
> +    val province: ProvinceGermany
Yes definitely. Here as well, we aligned on a MVP approach. In the future we want to have a full fledged system with automatic fetching of provinces of every country, fetching holidays etc.

2021-04-07 17:36 UTC, simon-ittmann commented on backend/src/main/kotlin/de/byteleaf/companyon/user/constant/ProvinceGermany.kt
> +    NORDREIN_WESTFALEN,
I will talk to Armin Laschet, I think its easier if we rename the province, instead of changing the code 💯

2021-04-08 07:43 UTC, ptolstoi approved these changes
👍

2021-04-08 09:06 UTC, merged